### ISSUE TITLE
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

### ISSUE THREAD

**Issue by Timple** [Rayman/ros-get#107]
I tried to init a workspace using the standard rosdistro:

```
$ ros-get ws-create https://github.com/ros/rosdistro /opt/ros/melodic/
-----------------------------------------------------
Profile:                     default
Extending:        [explicit] /opt/ros/melodic
Workspace:                   /home/tim/ros-ws
-----------------------------------------------------
Knip
Bla bla catkin stuff 
Knip
[build]   Abandoned: None.                                                                             
[build]   Failed:    None.                                                                             
[build] Runtime: 2.3 seconds total.                                                                    
[INFO] root: symlink '/home/tim/ros-ws' => '/home/tim/.config/ros-get/workspaces/ros-ws'
[INFO] ros_get.workspace: saved the workspace as 'ros-ws'
[INFO] ros_get.workspace: created first workspace, let's make it the default
[INFO] root: symlink 'workspaces/ros-ws' => '/home/tim/.config/ros-get/workspace'
Exception ignored in: <bound method BaseEventLoop.__del__ of <_UnixSelectorEventLoop running=False closed=True debug=False>>
Traceback (most recent call last):
  File "/home/tim/.local/lib/python3.6/site-packages/trollius/base_events.py", line 395, in __del__
  File "/home/tim/.local/lib/python3.6/site-packages/trollius/unix_events.py", line 65, in close
  File "/home/tim/.local/lib/python3.6/site-packages/trollius/unix_events.py", line 166, in remove_signal_handler
  File "/usr/lib/python3.6/signal.py", line 47, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

**Comment by reinzor** [comment]
Not sure if related but your ros index url seems to be wrong. It should be:

```
https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
```

**Comment by Timple** [comment]
Same error :slightly_smiling_face:

**Comment by reinzor** [comment]
See a same error [here](https://gist.github.com/drmaj/20b365ddd3c4d69e37c79b01ca17587a). Might be related to python3 on 18.04. We are running python3 on 20.04 without any issues.

**Comment by Timple** [comment]
Yes, python2 works. This can be closed.

Curious though why python3 doesn't work on 20.04 in a dockerfile?

```
FROM ubuntu:20.04
RUN apt-get update -qq && apt-get install -qqy python3-pip 
RUN python3 -m pip install ros-get
RUN ros-get ws-create https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml /opt/ros/noetic/
```

**Comment by reinzor** [comment]
That is due to the `catkin_tool` version that is shipped with ubuntu, see https://github.com/Rayman/ros-get/issues/95

**Comment by reinzor** [comment]
And another thing, `ubuntu:20.04` does not have the `/opt/ros/noetic` install space.

This seems to work:

```
FROM ros:noetic-ros-base
RUN apt-get update -qq && apt-get install -qqy python3-pip git 
RUN python3 -m pip install ros-get git+https://github.com/catkin/catkin_tools.git
RUN ros-get ws-create https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml /opt/ros/noetic/
```

**Comment by Timple** [comment]
> That is due to the catkin_tools version that is shipped with ubuntu, see #95

Should have remembered that I guess. As I posted the workaround there :smile: 

I'll put in a PR updating the README.md
