### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'buildlist'

### ISSUE THREAD

**Issue by rokusottervanger** [Rayman/ros-get#111]
Running `ros-get ws-create`:
```
Traceback (most recent call last):
  File "/home/rokus/.local/bin/ros-get", line 8, in <module>
    sys.exit(main())
  File "/home/rokus/.local/lib/python3.8/site-packages/ros_get/__main__.py", line 169, in main
    return func(**vars(args))
  File "/home/rokus/.local/lib/python3.8/site-packages/ros_get/workspace.py", line 64, in create
    result = create_workspace_with_catkin_tools(extend_path, dir)
  File "/home/rokus/.local/lib/python3.8/site-packages/ros_get/workspace.py", line 196, in create_workspace_with_catkin_tools
    if catkin_config.main(
  File "/usr/lib/python3/dist-packages/catkin_tools/verbs/catkin_config/cli.py", line 168, in main
    if opts.buildlist is not None:
AttributeError: 'Namespace' object has no attribute 'buildlist'
```

**Comment by Rayman** [comment]
Which OS and Python version?

**Comment by rokusottervanger** [comment]
Ubuntu 20.04, Python 3.8.10, catkin_tools 0.9.2
