### ISSUE TITLE
Assert

### ISSUE THREAD

**Issue by reinzor** [Rayman/ros-get#54]
```
Traceback (most recent call last):
  File "/home/rein/.local/bin/ros-get", line 11, in <module>
    load_entry_point('ros-get', 'console_scripts', 'ros-get')()
  File "/home/rein/.ros-get/src/ros_get/__main__.py", line 126, in main
    exit(func(**vars(args)))
  File "/home/rein/.ros-get/src/ros_get/commands.py", line 42, in update
    pkgs_done = recursive_update(pkgs, verbose)
  File "/home/rein/.ros-get/src/ros_get/commands.py", line 156, in recursive_update
    update_folder(target_path, {repo.name: repo}, verbose)
  File "/home/rein/.ros-get/src/ros_get/utils.py", line 85, in update_folder
    assert client.get_url() == url
AssertionError

```

**Comment by Rayman** [comment]
Was fixed by d0de4f80ec1a49e103ffb934f8f524d1c943dd19
