### ISSUE TITLE
[Python3] SyntaxError: invalid syntax def async

### ISSUE THREAD

**Issue by Rayman** [Rayman/ros-get#95]
In a fresh noetic container:
```
$ ros-get
Traceback (most recent call last):
  File "/usr/local/bin/ros-get", line 5, in <module>
    from ros_get.__main__ import main
  File "/usr/local/lib/python3.8/dist-packages/ros_get/__init__.py", line 1, in <module>
    from .commands import install, update, status, list_packages, remove
  File "/usr/local/lib/python3.8/dist-packages/ros_get/commands.py", line 13, in <module>
    from .workspace import ws_file
  File "/usr/local/lib/python3.8/dist-packages/ros_get/workspace.py", line 6, in <module>
    from catkin_tools.metadata import find_enclosing_workspace
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/metadata.py", line 22, in <module>
    from .common import mkdir_p
  File "/usr/local/lib/python3.8/dist-packages/catkin_tools/common.py", line 23, in <module>
    import trollius as asyncio
  File "/usr/local/lib/python3.8/dist-packages/trollius/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/local/lib/python3.8/dist-packages/trollius/base_events.py", line 42, in <module>
    from . import tasks
  File "/usr/local/lib/python3.8/dist-packages/trollius/tasks.py", line 565
    def async(coro_or_future, loop=None):
        ^
SyntaxError: invalid syntax
```

**Comment by Timple** [comment]
apt _and_ pip3 versions of catkin are broken for noetic. Workaround is to install like this:
sudo pip3 install git+https://github.com/catkin/catkin_tools.git  # apt not functional yet

**Comment by Rayman** [comment]
Thanks you!

**Comment by Rayman** [comment]
The issue is tracked here: https://github.com/catkin/catkin_tools/issues/594

**Comment by Timple** [comment]
Not sure why this doesn't get more noise. Lots of noetic activity but very little complaints about catkin_tools...

**Comment by Rayman** [comment]
Haha, could people be still using `catkin_make`?

**Comment by ashwani-rathee** [comment]
Thank you for the instructions,it worked :) I first tried apt in ubuntu20.04,then went with pip 3,both unsuccessfull then came here and this one worked well...

**Comment by liamreneroy** [comment]
@Timple thank you thank you. I dont understand how this isn't documented anywhere else. Really appreciate the tip, cheers

**Comment by Timple** [comment]
Actually there is a solution at the moment using apt:

```
sudo apt install python3-catkin-tools python3-osrf-pycommon
```
